fulcrum-mainnet:
  build: .
  dockerfile: Dockerfile
  container_name: fulcrum-mainnet
  volumes:
    - /mnt/data/blockchain-data/fulcrum/bchn-fulcrum/blockchain:/home/safeuser/blockchain
  ports:
    - 50001:50001
    - 50002:50002
  restart: always
