fulcrum-testnet:
  build: .
  dockerfile: Dockerfile
  container_name: fulcrum-testnet
  volumes:
    #- /mnt/usb/fulcrum/testnet-blockchain:/home/safeuser/blockchain
    - ../../blockchain:/home/safeuser/blockchain
  ports:
    - 60001:50001
    - 60002:50002
  restart: always

fulcrum-rest-api:
  build: ./rest-api
  dockerfile: Dockerfile
  container_name: fulcrum-rest-api
  ports:
    - 3000:3000
  links:
    - fulcrum-mainnet
  restart: always
