fulcrum-testnet:
  build: .
  dockerfile: Dockerfile
  container_name: fulcrum-testnet
  volumes:
    - /mnt/usb/fulcrum/testnet-blockchain:/home/safeuser/blockchain
  ports:
    - 60001:50001
    - 60002:50002
